### ISSUE TITLE
Memory leakage when flying on a380x

### ISSUE THREAD

**Issue by Def9Infinite** [flybywiresim/simbridge#131] opened 2024-11-01 00:05 UTC
With Simbridge open, after 1 hr and 10 min into flight, MFS consumes ~**130GB** of RAM and still keep increasing
![image](https://github.com/user-attachments/assets/7218e364-19ed-4f7d-a3bb-1618e2c7967c)
Looks interesting.... did a bit of digging and found out that simbridge was using ~20 GB of RAM. Quite alot! 
So I shutoff simbridge, MEM usage peaked at 148GB (the rate of increase is quite high as it uses 18 more gig in 5 minutes)
![image](https://github.com/user-attachments/assets/2ccb4596-d22d-414d-9001-0343bc0604cb)
and after another 10 min of flying, looks like there is no more crazy RAM usage anymore, quite stable at 148GB
![image](https://github.com/user-attachments/assets/218bd37d-4a83-45e9-be72-dcc7e534c653)

Quite safe to assume that something from simbridge got a MEM Leak, would be nice to have a look at since a380x launch more people will fly longhaul and this may crash sim

**Comment by JasonO99** [comment] 2024-11-01 00:08
Possibly duplicate of #84

**Comment by Def9Infinite** [comment] 2024-11-01 00:24
And after another few minutes of wait.... looks like it got picked up and cleaned
![image](https://github.com/user-attachments/assets/91feb68e-3d78-46a6-b9db-0a43ee1f121f)

**Comment by Def9Infinite** [comment] 2024-11-01 00:31
@JasonO99 Could be but looks like this is behaving a bit differently (also since this is on a38x not 320 thus decide to open a new issue)

**Comment by Saschl** [comment] 2024-11-14 08:12
@Def9Infinite there have been some fixes on the plane side which might have fixed this issue. I will close it for now, if you experience issues again, feel free to reopen this issue :)

**Closed by Saschl** 2024-11-14 08:12 UTC
